name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_NAME: palashshah606/weather_s3

jobs:
  build:
    runs-on: ubuntu-latest  # Or another desired runner OS

    steps:
      - uses: actions/checkout@v3  # Checkout your code from the repository

      - name: Set up JDK 17  # Change version if needed
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: 'maven'  # Optionally cache Maven packages

      - name: Build with Maven
        run: mvn package -DskipTests

#      # Step 4: Set up Docker Buildx
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      # Step 5: Log in to Docker Hub
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      # Step 6: Build and push the Docker image
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          platforms: linux/amd64
#          push: true
#          tags: |
#            ${{ env.IMAGE_NAME }}:latest
#            ${{ env.IMAGE_NAME }}:${{ github.sha }}
